name: Contrast Securtiy Dependency Analysis

on:
  pull_request:
  push:

jobs:
  contrast-security-dependency-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: security // contrast // checkout
        uses: actions/checkout@v3
        
      - name: security // contrast // dependency-check
        uses: Contrast-Security-OSS/contrast-sca-action@v1
        with: 
          apiKey: ${{ secrets.CONTRAST_API_KEY }}
          orgId: ${{ secrets.CONTRAST_ORGANIZATION_ID }}
          authHeader: ${{ secrets.CONTRAST_AUTH_HEADER }}
          apiUrl: ${{ secrets.CONTRAST_API_URL }}
          filePath: go.mod
          severity: medium
          fail: false
